backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
search: false

collections:
  - name: 'website'
    label: 'Website'
    files:
      - label: "Pages"
        name: "pages"
        file: "content/pages.json"
        fields:
          - label: Title
            name: title
            widget: string
          - label: Blocks
            name: blocks
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: markdown
                required: false
                buttons: ['bold', 'bulleted-list', 'numbered-list']
                editor_components: []
                modes: ['rich_text']
              - name: "cta"
                label: "Call to action"
                widget: "object"
                collapsed: false
                fields: 
                  - name: 'cta-label'
                    label: "Label"
                    required: false
                    widget: "string"
                  - name: 'cta-url'
                    label: "Url (https://...)"
                    required: false
                    widget: "string"
