backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
