backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
search: false

collections:
  - name: 'pages'
    label: 'Pages'
    files: 
      - name: 'block'
        label: 'Block'
        file: 'content/blocks.json'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            required: false
            widget: 'markdown'
            buttons: ['bold', 'bulleted-list', 'numbered-list']
            editor_components: []
            modes: ['rich_text']
          - name: "cta"
            label: "Call to action"
            widget: "object"
            collapsed: false
            fields: 
              - name: 'cta-label'
                label: "Label"
                required: false
                widget: "string"
              - name: 'cta-url'
                label: "Url (https://...)"
                required: false
                widget: "string"
