backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'blocks'
    label: 'blocks'
    folder: 'content/blocks'
    fields:
      - label: Page name
        name: pageName
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: markdown
      - label: CTA Label
        name: ctaLabel
        widget: string
      - label: CTA Link
        name: ctaLink
        widget: string
      - label: Order
        name: order
        widget: number
        value_type: int
        min: 1
